language: crystal
env:
  global:
  - secure: hN7Wumy7UAZjJxEsdnUHkvwxxV6k/UAAmQNZachwB0dbwzRNKBtEvVFmXiqMiUUcWtq8dNGGi17HglB4ZGd202dfykfL0vGB/DRTFeQ42oZtm1zulSlz27qdgkUUxOEP0Hzm4as8VYen3iUK3f6eumsmSRkFHiV7J3cnWsI2IpgDIvNEfCV3xXO/eMlCNz1z4ksTW0Gwb3RuEowxULhT11pKzzHQLWIXVzTpuDLtOvNHmUG+ob7eGXfyTSpYSRnEYhe0nRcZhKRgvOLdTWLEzaajiZQBZXXItZc+QQ+uX+NqBkPo4iJmQasEb+6tZ12s8RYbUt2sDi1gihCz7ZQeG8BiGVS19hPupIEbIKx9sMIFA+ASImBr/Ox36wKMFN+oluFrpuJ6viFLoMrA0rmpAKO1nXDP2z0VU43N9cU0HjebqPq/vecF3Y+vxnbZWXx+I3r1s9/DjG+hZrzsu8QLbjz4iCS10wez0IgmGg1Y6n7UfSho/6RxT+k0Fdd45X+tUGN9iSUsz6i6RXBa76kXF0fq5Tj1yFv4wCpaUV3DEUsr3W9lI86hpvEtJ7Q8qcEOzwV5PdsrSalAfJZG49aPd+dvItCZ25t/BgpXZx2ZZi/5INg9tQL/1eHB+DGmTU/H9Wsobzd3UDX4+8kXFJcMnmWCqg5lNPDGH8RjpY18Fxc=
  - secure: gtzm7dmvNDwxpqYZvy4ALM20RMOaNix0qf1FE+yq/9N95s2BhKdKGXeiJ09ZdAkiAgSkxI7F97QUeOm7dwVMYBcThtoy+t6wrhdab1aFNU/M7yUZHXWscvGOv1abaH3JCYv36rSRDzPMxKqVSgGzz9RM01Dxu16q4Lzn4uOsUn5Q5Fcg84/DQAQPgxQgIFzACWNR/Mkk39Aj2agJqEfrgTd3aIx0Vl8+gLihdHgDrEu5szQ0GDLM41BXTNqaG8Gh/C1eNN+vpj9bI+0+MgdMLDT+EVTywJ9yOnJP4vg1p75btlTfuPeBlAvADIrrMPcTqI5t4hgn6dRUmcWDh1HVPKY9pDOiA88UDbVDwQ0063lptXZ//tgoPi83rXA+WU6T5Gmh30PZv3zZYgqmKIJk3owp0lpZAxa00saxaUKoZw/aQ7xhqUlI7CT5kNS18eS6q25p4hHGc5AL61YSpBOLyMDF2DOj81N8EEkWhlzP236D5CLcWhL8QaOI1yHhL839n9H1TDhwQDCc9clIKwCOD8tmMDrI/QwW1uUh3Qr3cIHgwiKpjmCCsXWi+sPTQwMtitsriO8/fpSiIwbB3Jf0Ke7YruKdQ0xL61+PHNzfsYYqQblQNgIVuOwVgzFHpRUnCxTCNrbI+H+H/1bxbTZ+f+RsCX38tHeL03IED/rVEKk=
  matrix:
  - TIPBOT_ENV=test
script:
- crystal spec
- crystal tool format --check src
- crystal tool format --check spec
- bin/ameba
services:
- docker
deploy:
  provider: script
  script: bash scripts/deploy_to_docker.bash
  skip_cleanup: true
  on:
    branch: remaster
